"""Add hashed_password column to users

Revision ID: 3a3bcaa0aedb
Revises: 5be6c6c4a32e
Create Date: 2025-03-30 18:53:53.826224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3bcaa0aedb'
down_revision: Union[str, None] = '5be6c6c4a32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')  # Удаление столбца 'role'
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###

